### ISSUE TITLE
Change OperationId to be base64Url encoded

### ISSUE THREAD

**Issue by dhelmert** [upb-uc4/api#103]
Currently, the operationId can be in the url. Since the default base64 encoding contains slashes, the url gets broken. Therefore, use base64 specifically for urls, to circumvent this issue.

**Comment by matthias-geuchen** [comment]
Was this issue resolved?

**Comment by dhelmert** [comment]
> 
> 
> Was this issue resolved?

Yes, this is now resolved. Thanks for the reminder
