### ISSUE TITLE
Rename Endpoints in UserService

### ISSUE THREAD

**Issue by lrschaef** [upb-uc4/api#6]
- The following endpoints were edited:
- users was removed before students/lecturers/admins endpoints
- role endpoint was changed to: /role/<username>

- Lagom:
  - [x] implemented functional behaviour [API tag v0.4.0 Lagom tag v0.4.1]
  - [x] implemented completely [API tag v0.4.0 Lagom tag v0.4.1]
  - [x] unit tested [API tag v0.4.0 Lagom tag v0.4.1]

- Vue: 
  - [ ] implemented functional behaviour [API tag v0.4.0 Vue tag vX.X.X]
  - [ ] implemented completely [API tag v0.4.0 Vue tag vX.X.X]
  - [ ] unit tested [API tag v0.4.0 Vue tag vX.X.X]

**Comment by david-buderus** [comment]
In Lagom version v0.4.1 is the get all users endpoint wrong.

Will be fixed in v0.4.2

**Comment by lrschaef** [comment]
Is implemented
