### ISSUE TITLE
Add missing Signature to clearly define Unsigned-Transaction-API

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/api#70]
[.. ] working with protobuffer is dirty
[.. ] would be simpler to have byteArrays
[.. ] would be easy to just send strings
[.. ] need very specific definition

**Comment by david-buderus** [comment]
I would say the best way is, we are only using byte arrays.
In this way, lagom does not need to know how the hlf-api interacts with hlf and
the hlf-api does not need to know how lagom interacts with the front-end.
